def test_insert_rows():
    rows = [
        [
            "红 Red",
            "爱情",
            "三岛有纪子",
            "7.3",
            "16698",
            "https://movie.douban.com/subject/30465916/",
        ],
        [
            "赤焰战场 Red",
            "喜剧/动作/惊悚/犯罪",
            "罗伯特·施文特克",
            "7.6",
            "106051",
            "https://movie.douban.com/subject/3104794/",
        ],
        [
            "赤焰战场2 Red 2",
            "喜剧/动作/犯罪",
            "迪恩·帕里索",
            "7.3",
            "82368",
            "https://movie.douban.com/subject/7916027/",
        ],
        [
            "红色 Red",
            "剧情",
            "迈克尔·格兰达吉",
            "8.6",
            "2100",
            "https://movie.douban.com/subject/30451891/",
        ],
        [
            "青春变形记 Turning Red",
            "喜剧/动画/奇幻/冒险",
            "石之予",
            "8.0",
            "346586",
            "https://movie.douban.com/subject/35284253/",
        ],
        [
            "雷德怒潮 Red",
            "剧情/惊悚",
            "Trygve Allister Diesen",
            "7.2",
            "1612",
            "https://movie.douban.com/subject/3011107/",
        ],
        [
            "小红帽 Red",
            "动画/短片/奇幻",
            "Julio Jaramillo",
            "7.1",
            "370",
            "https://movie.douban.com/subject/10577735/",
        ],
        [
            "炽烈 Red",
            "剧情/短片",
            "德尔·凯瑟琳·巴顿",
            "8.0",
            "106",
            "https://movie.douban.com/subject/26915204/",
        ],
        [
            "红色杀机 Red",
            "动作/惊悚",
            "Thirumala Kishore",
            "6.5",
            "111",
            "https://movie.douban.com/subject/35022519/",
        ],
        [
            "红 Red",
            "短片/同性",
            "蒋鸿宇",
            "暂无评分",
            "0",
            "https://movie.douban.com/subject/27166982/",
        ],
        [
            "雨花错 Red",
            "剧情/动画/短片/战争",
            "陶志强",
            "6.7",
            "75",
            "https://movie.douban.com/subject/11516704/",
        ],
        [
            "Red",
            "剧情/喜剧/冒险",
            "未知",
            "暂无评分",
            "0",
            "https://movie.douban.com/subject/35639264/",
        ],
        [
            "赤潮",
            "短片",
            "章德音",
            "暂无评分",
            "0",
            "https://movie.douban.com/subject/35231971/",
        ],
        [
            "赤焰战场 Red",
            "未知",
            "未知",
            "暂无评分",
            "0",
            "https://movie.douban.com/subject/26592584/",
        ],
        [
            "红 Red",
            "悬疑/惊悚/短片",
            "Alexandre Charleux",
            "暂无评分",
            "0",
            "https://movie.douban.com/subject/25758710/",
        ],
    ]

    return rows
